services:
    syncthing:
        container_name: sync
        image: syncthing/syncthing:1.23.0
        restart: unless-stopped
        environment:
            - PUID=2001
            - PGID=2001
        ports:
            - 8384:8384 # Web
            - 22000:22000/tcp # TCP file transfers
            - 22000:22000/udp # QUIC file transfers
            - 21027:21027/udp # Receive local discovery broadcasts
        volumes:
            - /var/docker/backup/syncthing/files:/var/syncthing/files # Synced files
            - /var/docker/backup/syncthing/config:/var/syncthing/config # Syncthing configurations