# Modified from official production docker-compose file:
# https://github.com/inventree/InvenTree/blob/master/docker/production/docker-compose.yml

services:
    inventree-cache:
        container_name: inventree-cache
        image: redis:7.0.8-alpine3.17
        profiles:
            - redis
            - postgres
        depends_on:
            - inventree-db
        networks:
            - inventree
    
    inventree-db:
        container_name: inventree-db
        image: postgres:15.2-alpine3.17
        profiles:
            - postgres
        environment:
            # Needs to match with .env file if enabled
            - POSTGRES_USER=inventree
            - POSTGRES_PASSWORD=pgpassword
            - POSTGRES_DB=inventree
        networks:
            - inventree
        volumes:
            - /var/docker/management/inventree/db:/var/lib/postgresql/data
    
    inventree-server:
        container_name: inventree-server
        image: inventree/inventree:0.10.1
        env_file:
            - .env
        networks:
            - inventree
        volumes:
            - inventree-app:/home/inventree/data
        
    inventree-worker:
        container_name: inventree-worker
        image: inventree/inventree:0.10.1
        command: invoke worker
        depends_on:
            - inventree-server
        env_file:
            - .env
        volumes:
            - inventree-app:/home/inventree/data
    
    inventree-endpoint:
        container_name: inventree-endpoint
        image: nginx:1.23.3-alpine
        networks:
            - inventree
            - outpost
        volumes:
            - inventree-app:/var/www
            - type: bind
              source: /var/docker/management/inventree/nginx.conf # Create before use
              target: /etc/nginx/conf.d/default.conf

networks:
    # To Outpost (i.e. reverse proxy)
    outpost:
    # For InvenTree internal connection
    inventree:

volumes:
    inventree-app:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /var/docker/management/inventree/app # Create before use